config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  resources :reviews, only: [:destroy]
end

# same

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  # def review
  #   @review = @restaurant.review
  # end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path, notice: 'Your restaurant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant
  # except: :destroy ???????

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%# error notifications on thiers, otherwise same %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions btn btn-primary btn-sm">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Show 👀', @restaurant %>
<%= link_to '🔸 Go ⏪ 🔸 (🔙)', restaurants_path %>

<%# same %>

app/views/restaurants/index.html.erb
<%# they have a <p> with id="notice"??? %>
<%# theirs is a table, otherwise same %>
<h1>Restaurants</h1>
<% @restaurants.each do |restaurant| %>
<%# change to each_with_index for style? 1. etc... %>
  <h5><%= restaurant.name %> - <%= '⭐️' * rand(1..5) %> - <%= restaurant.category %></h5>
<% end %>
<p>Here are your <%= @restaurants.count %> restaurants!</p>

<%= link_to 'Add new restaurant', new_restaurant_path %>

<%# add links to edit and delete and related code %>
<%# THEIRS: %>
<%# <%= link_to 'Show', restaurant %> %>
<%# <%= link_to 'Edit', edit_restaurant_path(restaurant) %> %>
<%# <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %> %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to '🔸 Go ⏪ 🔸 (🔙)', restaurants_path %>

<%# same %>

app/views/restaurants/show.html.erb
<h1>Restaurant: <%= @restaurant.name %></h1>
<h4>Rating:<%= '⭐️' * rand(1..5) %></h4>
<h4>Cuisine: <%= @restaurant.category %></h4>
<p>  ---> Mmm yum!</p>


<ul class='list-group'>
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <%= review.content %>
      <%= link_to 'Delete', restaurant_review_path(review), method: :delete %>
    <%# theirs is review_path(review) - but i dont have that path??? %>
    </li>
  <% end %>
</ul>

<%= link_to 'Add a new review', new_restaurant_review_path(@restaurant) %>
<br>
<%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant) %>
<br>
<%= link_to '🔸 Go ⏪ 🔸 (🔙)', restaurants_path %>
<%# otherwise same %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>

  <%= f.input :rating, as: :select, collection: [1, 2, 3, 4, 5] %>

  <div class="form-actions btn btn-primary mt-2 mx-2 mb-2">
    <%= f.button :submit %>
  </div>

<% end %>


<%= link_to '🔸 Go ⏪ 🔸 (🔙)', restaurants_path %>

<%# different but bc its better not bc its wrong %>